---
title: "dashboard_1"
author: "Vasili Fokaidis"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r}
library(tidyverse)
library(gganimate)
library(flexdashboard)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

mtm_2017_acs_2017_race_df = read.csv("mtm_2017_acs_2017_race_df.csv")
mtm_2017_edu_2017_att_df = read.csv("mtm_2017_edu_2017_att_df.csv")
mtm_2017_income_2017_brac_df = read.csv("mtm_2017_income_2017_brac_df.csv")
mtm_2017_ins_2017_status_df = read.csv("mtm_2017_ins_2017_status_df.csv")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r}
race_per_plot =
  
mtm_2017_acs_2017_race_df %>%
  pivot_longer(
    white:hispanic,
    names_to = "race",
    values_to = "percents"
  ) %>%
  mutate(
    race = str_replace(race, "white", "White"),
    race = str_replace(race, "black", "Black"),
    race = str_replace(race, "am_ind_al_nat", "American Indian and Alaska Native"),
    race = str_replace(race, "asian", "Asian"),
    race = str_replace(race, "nat_ha_pac_isl", "Native Hawaiian and Other Pacific Islander"),
    race = str_replace(race, "other", "Other Race"),
    race = str_replace(race, "two_or_more", "Two or More Races"),
    race = str_replace(race, "hispanic", "Hispanic")
    ) %>%
  select(geo_id, total, race, percents, fi_rate) %>%
  drop_na() %>%
  ggplot(aes(x = fi_rate, y = percents, size = total, color = race)) + 
  geom_point(show.legend = FALSE, alpha = 0.8) +
  labs(
    title = '{closest_state}',
    x = "Food Insecurity Rate",
    y = "% Race Within Each County"
  ) +
  theme_bw() +
  transition_states(race, transition_length = 1, state_length = 3, wrap = TRUE) + 
  enter_fade() + 
  exit_fade() +
  ease_aes('cubic-in-out')

animate(race_per_plot, fps = 5, height = 500, width = 1000)
```

Column
-----------------------------------------------------------------------

### Chart B
```{r}
edu_per_plot =
  
mtm_2017_edu_2017_att_df %>%
  pivot_longer(
    less_9th:grad_or_prof,
    names_to = "edu_att",
    values_to = "percents"
  ) %>%
  mutate(
    edu_att = str_replace(edu_att, "less_9th", "Less Than 9th Grade"),
    edu_att = str_replace(edu_att, "nineth_to_12th", "9th to 12th Grade"),
    edu_att = str_replace(edu_att, "hs_grad", "High School Graduate"),
    edu_att = str_replace(edu_att, "some_coll", "Some College"),
    edu_att = str_replace(edu_att, "assoc_deg", "Associate's Degree"),
    edu_att = str_replace(edu_att, "bach_deg", "Bachelor's Degree"),
    edu_att = str_replace(edu_att, "grad_or_prof", "Graduate or Professional Degree")
    ) %>%
  select(geo_id, total, edu_att, percents, fi_rate) %>%
  drop_na() %>%
  ggplot(aes(x = fi_rate, y = percents, size = total, color = edu_att)) + 
  geom_point(show.legend = FALSE, alpha = 0.8) +
  labs(
    title = '{closest_state}',
    x = "Food Insecurity Rate",
    y = "% Education Attainment Within Each County"
  ) +
  theme_bw() +
  transition_states(edu_att, transition_length = 1, state_length = 3, wrap = TRUE) + 
  enter_fade() + 
  exit_fade() +
  ease_aes('cubic-in-out')

animate(edu_per_plot, fps = 5, height = 500, width = 1000)
```

Column
-----------------------------------------------------------------------

### Chart C
```{r}
ins_status_plot =
  
mtm_2017_ins_2017_status_df %>%
  select(-tot_19_64, -tot_under_19, - tot_65_over) %>%
  pivot_longer(
    y_under_19:n_65_over,
    names_to = "ins_status",
    values_to = "percents"
  ) %>%
  mutate(
    ins_status = str_replace(ins_status, "y_under_19", "Under Age 19 With Insurance"),
    ins_status = str_replace(ins_status, "n_under_19", "Under Age 19 Without Insurance"),
    ins_status = str_replace(ins_status, "y_19_64", "Ages 19 to 64 With Insurance"),
    ins_status = str_replace(ins_status, "n_19_64", "Ages 19 to 64 Without Insurance"),
    ins_status = str_replace(ins_status, "y_65_over", "Over Age 65 With Insurance"),
    ins_status = str_replace(ins_status, "n_65_over", "Over Age 65 Without Insurance"),
    ) %>%
  select(geo_id, total, ins_status, percents, fi_rate) %>%
  drop_na() %>%
  ggplot(aes(x = fi_rate, y = percents, size = total, color = ins_status)) + 
  geom_point(show.legend = FALSE, alpha = 0.8) +
  labs(
    title = '{closest_state}',
    x = "Food Insecurity Rate",
    y = "% of Individuals"
  ) +
  theme_bw() +
  transition_states(ins_status, transition_length = 1, state_length = 3, wrap = TRUE) + 
  enter_fade() + 
  exit_fade() +
  ease_aes('cubic-in-out')

animate(ins_status_plot, fps = 5, height = 500, width = 1000)
```


Column
-----------------------------------------------------------------------

### Chart D
```{r}
income_brac_plot =
  
mtm_2017_income_2017_brac_df %>%
  pivot_longer(
    less_20:twohun_more,
    names_to = "income_brac",
    values_to = "percents"
  ) %>%
  mutate(
    income_brac = str_replace(income_brac, "less_20", "Less Than $20,000"),
    income_brac = str_replace(income_brac, "twenty_39", "Between $20,000 and $39,999"),
    income_brac = str_replace(income_brac, "forty_59", "Between $40,000 and $59,999"),
    income_brac = str_replace(income_brac, "sixty_99", "Between $60,000 and $99,999"),
    income_brac = str_replace(income_brac, "hun_149", "Between $100,000 and $149,999"),
    income_brac = str_replace(income_brac, "hunfifty_199", "Between $150,000 and $199,999"),
    income_brac = str_replace(income_brac, "twohun_more", "$200,000 or More")
    ) %>%
  select(geo_id, total, income_brac, percents, fi_rate) %>%
  drop_na() %>%
  ggplot(aes(x = fi_rate, y = percents, size = total, color = income_brac)) + 
  geom_point(show.legend = FALSE, alpha = 0.8) +
  labs(
    title = '{closest_state}',
    x = "Food Insecurity Rate",
    y = "% of Individuals in Each Income Bracket"
  ) +
  theme_bw() +
  transition_states(income_brac, transition_length = 1, state_length = 3, wrap = TRUE) + 
  enter_fade() + 
  exit_fade() +
  ease_aes('cubic-in-out')

animate(income_brac_plot, fps = 5, height = 500, width = 1000)
```