---
title: "County Maps"
output:
  html_document:
    toc: false
    toc_float: false
runtime: shiny
---

```{r import libraries}
library(tidyverse)
library(plotly)
library(rjson)
library(rvest)
library(httr)
library(usdata)
library(shiny)
library(leaflet)
```



```{r fips data}
fips_df = readxl::read_xls("./fips_data/US_FIPS_Codes.xls", skip = 1) %>%
  janitor::clean_names() %>%
  rename(county = county_name) %>%
  unite("fips", c("fips_state", "fips_county"), sep = "") %>%
  mutate(county = tolower(county),
         state = state2abbr(state),
         county = str_replace(county, ",.*", ""),
         county = str_replace(county, "\\scounty",""),
         county = str_replace(county, "\\sparish",""),
         county = str_replace(county, "\\sborough", ""),
         county = str_replace(county, "\\scensus area", ""),
         county = str_replace(county, "\\smunicipality of", ""),
         county = str_replace(county, "dona ana", "doña ana"),
         county = str_replace(county, "^st\\s|^st\\.", "saint "),
         county = str_replace(county, "de kalb", "dekalb")
  ) %>%
unite("county_state", c("county", "state"), sep = "_", remove = FALSE) %>%
  mutate(county_state = str_replace(county_state, "prince of wales-outer ketchikan_AK", "prince of wales-hyder_AK"),
         county_state = str_replace(county_state, "matanuska susitna_AK", "matanuska-susitna_AK"),
         county_state = str_replace(county_state, "valdez cordova_AK", "valdez-cordova_AK"),
         county_state = str_replace(county_state, "juneau_AK", "city and of juneau_AK"),
         county_state = str_replace(county_state, "dekalb_TN", "de kalb_TN"),
         county_state = str_replace(county_state, "dekalb_IN", "de kalb_IN"),
         county_state = str_replace(county_state, "dewitt_IL", "de witt_IL"),
         county_state = str_replace(county_state, "de soto_MS", "desoto_MS"),
         county_state = str_replace(county_state, "de soto_FL", "desoto_FL"),
         county_state = str_replace(county_state, "du page_IL", "dupage_IL"),
         county_state = str_replace(county_state, "skagway hoonah angoon_AK", "hoonah-angoon_AK"),
         county_state = str_replace(county_state, "skagway hoonah angoon_AK", "hoonah-angoon_AK"),
         county_state = str_replace(county_state, "wrangell petersburg_AK", "petersburg_AK"),
         county_state = str_replace(county_state, "prince georges_MD", "prince george's_MD"),
         county_state = str_replace(county_state, "prince wales ketchikan_AK", "prince of wales-hyder_AK"),
         county_state = str_replace(county_state, "queen annes_MD", "queen anne's_MD"),
         county_state = str_replace(county_state, "radford_VA", "radford city_VA"),
         county_state = str_replace(county_state, "saint marys_MD", "saint mary's_MD"),
         county_state = str_replace(county_state, "yukon koyukuk_AK", "yukon-koyukuk_AK")
) %>%
  select(county_state, fips)


map_the_meal_gap_df = read_csv("./map_the_meal_gap_df.csv")

mtm_fips_df = left_join(map_the_meal_gap_df, fips_df, by = "county_state") %>%
  drop_na(fips)

```




```{r plot attempt 2}

year_choices = mtm_fips_df %>%
pull(year) %>% 
  unique() %>%
  sort()

selectInput(
  "year",
  h3("Year"),
  choices = year_choices
)

renderPrint(
  input[["year"]]
)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

z_df = mtm_fips_df %>%
  mutate(fi_rate = fi_rate * 100)

renderPlotly({
z_df %>% 
  dplyr::filter(year == rlang::sym(input[["year"]]))%>%
plot_ly() %>% 
  add_trace(
    type="choropleth",
    geojson=counties,
    locations=~(fips),
    z=~(fi_rate),
    colorscale="Viridis",
    zmin=0,
    zmax=40,
    marker=list(line=list(
      width=0)
    )
  ) %>%
  colorbar(title = "Food Insecurity Rate (%)") %>% 
  layout(
    title = "US Food Insecurity Rate by County",
    geo = g
)
})
```



```{r plot attempt 3}

year_choices = mtm_fips_df %>%
pull(year) %>% 
  unique() %>%
  sort()

selectInput(
  "year",
  h3("Year"),
  choices = year_choices
)

renderPrint(
  input[["year"]]
)

selectInput(
  "food insecurity metric",
  h3("Food Insecurity Metric"),
  choices = c("fi_rate", "number_food_insecure_individuals", "low_threshold_in_state", "high_threshold_in_state", "percent_fi_low_threshold", "percent_fi_btwn_thresholds", "percent_fi_high_threshold", "weighted_annual_food_budget_shortfall", "cost_per_meal", "child_fi_rate", "number_food_insecure_children", "percent_of_children_in_fi_hh_with_hh_incomes_below_185_percent_fpl", "percent_of_children_in_fi_hh_with_hh_incomes_above_185_percent_fpl")
)

renderPrint(
  input[["food insecurity metric"]]
)

url <- 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
counties <- rjson::fromJSON(file=url)

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

z_df = mtm_fips_df %>%
  mutate(fi_rate = fi_rate * 100,
         percent_fi_low_threshold = percent_fi_low_threshold * 100,
         percent_fi_btwn_thresholds = percent_fi_btwn_thresholds * 100,
         percent_fi_high_threshold = percent_fi_high_threshold * 100,
         child_fi_rate = child_fi_rate * 100,
         percent_of_children_in_fi_hh_with_hh_incomes_below_185_percent_fpl = percent_of_children_in_fi_hh_with_hh_incomes_below_185_percent_fpl * 100,
         percent_of_children_in_fi_hh_with_hh_incomes_above_185_percent_fpl = percent_of_children_in_fi_hh_with_hh_incomes_above_185_percent_fpl *100
  )

renderPlotly({
z_df %>% 
  dplyr::filter(year == rlang::sym(input[["year"]]))%>%
plot_ly() %>% 
  add_trace(
    type="choropleth",
    geojson=counties,
    locations=~(fips),
    z=~(eval(as.name(input[["food insecurity metric"]]))), 
    text = ~county_state,
    colorscale="Viridis",
    zmin=0,
    zmax=case_when(
  input[["food insecurity metric"]] == "fi_rate" ~ 40,
  input[["food insecurity metric"]] == "number_food_insecure_individuals" ~ 1749600,
  input[["food insecurity metric"]] == "low_threshold_in_state" ~ 2,
  input[["food insecurity metric"]] == "high_threshold_in_state" ~ 2,
  input[["food insecurity metric"]] == "percent_fi_low_threshold" ~ 100,
  input[["food insecurity metric"]] == "percent_fi_btwn_thresholds" ~ 78,
  input[["food insecurity metric"]] == "percent_fi_high_threshold"  ~ 100,
  input[["food insecurity metric"]] == "weighted_annual_food_budget_shortfall" ~ 815943000,
  input[["food insecurity metric"]] == "cost_per_meal" ~ 7,
  input[["food insecurity metric"]] == "child_fi_rate" ~ 53,
  input[["food insecurity metric"]] == "number_food_insecure_children" ~ 734490,
  input[["food insecurity metric"]] == "percent_of_children_in_fi_hh_with_hh_incomes_below_185_percent_fpl" ~ 100,
  input[["food insecurity metric"]] ==  "percent_of_children_in_fi_hh_with_hh_incomes_above_185_percent_fpl" ~ 100
),
    marker=list(line=list(
      width=0)
    )
  ) %>%
  colorbar(title = case_when(
  input[["food insecurity metric"]] == "fi_rate" ~ "Food Insecurity Rate (%)",
  input[["food insecurity metric"]] == "number_food_insecure_individuals" ~ "Number of Food Insecure Individuals",
  input[["food insecurity metric"]] == "low_threshold_in_state" ~ "Low Threshold in State",
  input[["food insecurity metric"]] == "high_threshold_in_state" ~ "High Threshold in State",
  input[["food insecurity metric"]] == "percent_fi_low_threshold" ~ "Food Insecurity Rate Low Threshold (%)",
  input[["food insecurity metric"]] == "percent_fi_btwn_thresholds" ~ "Food Insecurity Rate Between Threshold (%)",
  input[["food insecurity metric"]] == "percent_fi_high_threshold"  ~ "Food Insecurity Rate High Threshold (%)",
  input[["food insecurity metric"]] == "weighted_annual_food_budget_shortfall" ~ "Weighted Annual Food Budget Shortfall ($)",
  input[["food insecurity metric"]] == "cost_per_meal" ~ "Cost Per Meal ($)",
  input[["food insecurity metric"]] == "child_fi_rate" ~ "Child Food Insecurity Rate (%)",
  input[["food insecurity metric"]] == "number_food_insecure_children" ~ "Numver of Food Insecure Children",
  input[["food insecurity metric"]] == "percent_of_children_in_fi_hh_with_hh_incomes_below_185_percent_fpl" ~ "Children in Food Insecure Households with Household Incomes Below 185 Percent of the Federal Poverty Levell (%)",
  input[["food insecurity metric"]] ==  "percent_of_children_in_fi_hh_with_hh_incomes_above_185_percent_fpl" ~ "Children in Food Insecure Households with Household Incomes Above 185 Percent of the Federal Poverty Levell (%)"
)
           ) %>% 
  layout(
    title = "US Food Insecurity Metrics by County",
    geo = g
)
})
```


```{r food bank map}
food_banks_df = read_csv("./food_banks_df.csv")

#pal <- colorNumeric(
 # palette = "viridis",
#  domain = food_banks_df$name
#)

food_banks_df %>% 
  mutate(click_label = str_c("Name: ", name, "\nAddress: ", address_phone, " ", zip, "\nPhone Number: ", phone_number, "\nWebsite: ", "website_list", "County and State: ", county_state) 
         ) %>%
  leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(~latitude, ~longitude, radius = .1, popup = ~click_label)
  
```

