---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(gganimate)
library(flexdashboard)

mtm_2017_acs_2017_race_df = read.csv("mtm_2017_acs_2017_race_df.csv")
mtm_2017_edu_2017_att_df = read.csv("mtm_2017_edu_2017_att_df.csv")
mtm_2017_income_2017_brac_df = read.csv("mtm_2017_income_2017_brac_df.csv")
mtm_2017_ins_2017_status_df = read.csv("mtm_2017_ins_2017_status_df.csv")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
race_per_plot =
  
mtm_2017_acs_2017_race_df %>%
  pivot_longer(
    white:hispanic,
    names_to = "race",
    values_to = "percents"
  ) %>%
  mutate(
    race = str_replace(race, "white", "White"),
    race = str_replace(race, "black", "Black"),
    race = str_replace(race, "am_ind_al_nat", "American Indian and Alaska Native"),
    race = str_replace(race, "asian", "Asian"),
    race = str_replace(race, "nat_ha_pac_isl", "Native Hawaiian and Other Pacific Islander"),
    race = str_replace(race, "other", "Other Race"),
    race = str_replace(race, "two_or_more", "Two or More Races"),
    race = str_replace(race, "hispanic", "Hispanic")
    ) %>%
  select(geo_id, total, race, percents, fi_rate) %>%
  drop_na() %>%
  ggplot(aes(x = fi_rate, y = percents, size = total, color = race)) + 
  geom_point(show.legend = FALSE, alpha = 0.8) +
  labs(
    title = '{closest_state}',
    x = "Food Insecurity Rate",
    y = "% Race Within Each County"
  ) +
  theme_bw() +
  transition_states(race, transition_length = 1, state_length = 3, wrap = TRUE) + 
  enter_fade() + 
  exit_fade() +
  ease_aes('cubic-in-out')

animate(race_per_plot, fps = 5, height = 500, width = 1000)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

